FROM postgres:17-alpine

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=postal_db

EXPOSE 5432

COPY ./lab-1 /docker-entrypoint-initdb.d/
COPY ./lab-2 /docker-entrypoint-initdb.d/
COPY ./lab-3 /docker-entrypoint-initdb.d/