services:
    db_builder:
        image: db_builder_image:1
        container_name: db_builder
        build:
            context: .
            dockerfile: Dockerfile.db_builder
        volumes:
            - db_storage:/var/lib/postgresql/18/docker
        ports:
            - "15432:5432"

volumes:
    db_storage:
        driver: local