FROM registry.gitlab.com/dalibo/postgresql_anonymizer:stable

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=postal_db

EXPOSE 5432

COPY ./lab-1 /docker-entrypoint-initdb.d/
COPY ./lab-2 /docker-entrypoint-initdb.d/
COPY ./lab-3 /docker-entrypoint-initdb.d/ 
COPY ./lab-4 /docker-entrypoint-initdb.d/

COPY ./rgr-5 /docker-entrypoint-initdb.d/

COPY ./pre-lab-6 /docker-entrypoint-initdb.d/