services:
    db_builder:
        image: db_builder_image:1
        container_name: db_builder
        build:
            context: .
            dockerfile: Dockerfile.db_builder
        volumes:
            - db_storage:/var/lib/postgresql/18/docker
        ports:
            - "15432:5432"
        # command: |
        #     sh -c "
        #         docker-entrypoint.sh postgres \
        #         && ln -s /docker-entrypoint-initdb.d/gpg_keys /var/lib/postgresql/18/docker/gpg_keys
        #     "

volumes:
    db_storage:
        driver: local